/*
 * This file is generated by jOOQ.
 */
package com.pip.chatbot.jooq;


import com.pip.chatbot.jooq.tables.Forecast;
import com.pip.chatbot.jooq.tables.records.ForecastRecord;

import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>weather</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ForecastRecord, Integer> IDENTITY_FORECAST = Identities0.IDENTITY_FORECAST;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ForecastRecord> FORECAST_PKEY = UniqueKeys0.FORECAST_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<ForecastRecord, Integer> IDENTITY_FORECAST = Internal.createIdentity(Forecast.FORECAST, Forecast.FORECAST.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<ForecastRecord> FORECAST_PKEY = Internal.createUniqueKey(Forecast.FORECAST, "forecast_pkey", new TableField[] { Forecast.FORECAST.ID }, true);
    }
}
