/*
 * This file is generated by jOOQ.
 */
package com.pip.chatbot.jooq;


import com.pip.chatbot.jooq.tables.Forecast;


/**
 * Convenience access to all tables in weather
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>weather.forecast</code>.
     */
    public static final Forecast FORECAST = Forecast.FORECAST;
}
