CREATE SCHEMA IF NOT EXISTS fortune;
SET search_path TO fortune;

CREATE TABLE IF NOT EXISTS symbol(
	symbol VARCHAR(16) PRIMARY KEY,
	name VARCHAR(127) NOT NULL UNIQUE,
	is_currency BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS stock(
	id BIGSERIAL PRIMARY KEY,
	symbol VARCHAR(16) NOT NULL REFERENCES symbol(symbol) ON UPDATE CASCADE ON DELETE CASCADE,
	value REAL NOT NULL,
	date TIMESTAMP NOT NULL,
	is_historical BOOLEAN NOT NULL
);