CREATE SCHEMA IF NOT EXISTS finance;
SET search_path TO finance;

CREATE TABLE IF NOT EXISTS symbol(
	symbol VARCHAR(16) NOT NULL PRIMARY KEY,
	full_name VARCHAR(127) NOT NULL,
	is_currency BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS stock(
	id SERIAL PRIMARY KEY,
	symbol VARCHAR(16) NOT NULL REFERENCES symbol(symbol) ON UPDATE CASCADE ON DELETE CASCADE,
	value REAL NOT NULL,
	date TIMESTAMP NOT NULL,
	is_historical BOOLEAN NOT NULL
);