/*
 * This file is generated by jOOQ.
 */
package com.pip.chatbot.jooq.weather.tables.records;


import com.pip.chatbot.jooq.weather.tables.Country;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CountryRecord extends UpdatableRecordImpl<CountryRecord> implements Record1<String> {

    private static final long serialVersionUID = -1357599840;

    /**
     * Setter for <code>weather.country.country</code>.
     */
    public void setCountry(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>weather.country.country</code>.
     */
    public String getCountry() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Country.COUNTRY.COUNTRY_;
    }

    @Override
    public String component1() {
        return getCountry();
    }

    @Override
    public String value1() {
        return getCountry();
    }

    @Override
    public CountryRecord value1(String value) {
        setCountry(value);
        return this;
    }

    @Override
    public CountryRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CountryRecord
     */
    public CountryRecord() {
        super(Country.COUNTRY);
    }

    /**
     * Create a detached, initialised CountryRecord
     */
    public CountryRecord(String country) {
        super(Country.COUNTRY);

        set(0, country);
    }
}
