/*
 * This file is generated by jOOQ.
 */
package com.pip.chatbot.jooq.finance;


import com.pip.chatbot.jooq.DefaultCatalog;
import com.pip.chatbot.jooq.finance.tables.Stock;
import com.pip.chatbot.jooq.finance.tables.Symbol;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Finance extends SchemaImpl {

    private static final long serialVersionUID = 1630715438;

    /**
     * The reference instance of <code>finance</code>
     */
    public static final Finance FINANCE = new Finance();

    /**
     * The table <code>finance.stock</code>.
     */
    public final Stock STOCK = Stock.STOCK;

    /**
     * The table <code>finance.symbol</code>.
     */
    public final Symbol SYMBOL = Symbol.SYMBOL;

    /**
     * No further instances allowed
     */
    private Finance() {
        super("finance", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.STOCK_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Stock.STOCK,
            Symbol.SYMBOL);
    }
}
