/*
 * This file is generated by jOOQ.
 */
package com.pip.chatbot.jooq.finance;


import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in finance
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>finance.stock_id_seq</code>
     */
    public static final Sequence<Integer> STOCK_ID_SEQ = Internal.createSequence("stock_id_seq", Finance.FINANCE, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
