/*
 * This file is generated by jOOQ.
 */
package com.pip.chatbot.jooq.finance;


import com.pip.chatbot.jooq.finance.tables.Stock;
import com.pip.chatbot.jooq.finance.tables.Symbol;


/**
 * Convenience access to all tables in finance
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>finance.stock</code>.
     */
    public static final Stock STOCK = Stock.STOCK;

    /**
     * The table <code>finance.symbol</code>.
     */
    public static final Symbol SYMBOL = Symbol.SYMBOL;
}
