/*
 * This file is generated by jOOQ.
 */
package com.pip.chatbot.jooq.weather;


import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in weather
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>weather.forecast_id_seq</code>
     */
    public static final Sequence<Integer> FORECAST_ID_SEQ = Internal.createSequence("forecast_id_seq", Weather.WEATHER, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
