/*
 * This file is generated by jOOQ.
 */
package com.pip.chatbot.jooq.weather;


import com.pip.chatbot.jooq.weather.tables.City;
import com.pip.chatbot.jooq.weather.tables.Country;
import com.pip.chatbot.jooq.weather.tables.Forecast;


/**
 * Convenience access to all tables in weather
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>weather.city</code>.
     */
    public static final City CITY = City.CITY;

    /**
     * The table <code>weather.country</code>.
     */
    public static final Country COUNTRY = Country.COUNTRY;

    /**
     * The table <code>weather.forecast</code>.
     */
    public static final Forecast FORECAST = Forecast.FORECAST;
}
