/*
 * This file is generated by jOOQ.
 */
package com.pip.chatbot.jooq.weather;


import com.pip.chatbot.jooq.DefaultCatalog;
import com.pip.chatbot.jooq.weather.tables.City;
import com.pip.chatbot.jooq.weather.tables.Country;
import com.pip.chatbot.jooq.weather.tables.Forecast;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Weather extends SchemaImpl {

    private static final long serialVersionUID = -78760477;

    /**
     * The reference instance of <code>weather</code>
     */
    public static final Weather WEATHER = new Weather();

    /**
     * The table <code>weather.city</code>.
     */
    public final City CITY = City.CITY;

    /**
     * The table <code>weather.country</code>.
     */
    public final Country COUNTRY = Country.COUNTRY;

    /**
     * The table <code>weather.forecast</code>.
     */
    public final Forecast FORECAST = Forecast.FORECAST;

    /**
     * No further instances allowed
     */
    private Weather() {
        super("weather", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.FORECAST_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            City.CITY,
            Country.COUNTRY,
            Forecast.FORECAST);
    }
}
