/*
 * This file is generated by jOOQ.
 */
package com.pip.chatbot.jooq.fortune;


import com.pip.chatbot.jooq.DefaultCatalog;
import com.pip.chatbot.jooq.fortune.tables.Currency;
import com.pip.chatbot.jooq.fortune.tables.Stock;
import com.pip.chatbot.jooq.fortune.tables.Symbol;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Fortune extends SchemaImpl {

    private static final long serialVersionUID = 1325760814;

    /**
     * The reference instance of <code>fortune</code>
     */
    public static final Fortune FORTUNE = new Fortune();

    /**
     * The table <code>fortune.currency</code>.
     */
    public final Currency CURRENCY = Currency.CURRENCY;

    /**
     * The table <code>fortune.stock</code>.
     */
    public final Stock STOCK = Stock.STOCK;

    /**
     * The table <code>fortune.symbol</code>.
     */
    public final Symbol SYMBOL = Symbol.SYMBOL;

    /**
     * No further instances allowed
     */
    private Fortune() {
        super("fortune", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.STOCK_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Currency.CURRENCY,
            Stock.STOCK,
            Symbol.SYMBOL);
    }
}
