/*
 * This file is generated by jOOQ.
 */
package com.pip.chatbot.jooq.fortune;


import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in fortune
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>fortune.stock_id_seq</code>
     */
    public static final Sequence<Long> STOCK_ID_SEQ = Internal.createSequence("stock_id_seq", Fortune.FORTUNE, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
