/*
 * This file is generated by jOOQ.
 */
package com.pip.chatbot.jooq.fortune;


import com.pip.chatbot.jooq.fortune.tables.Stock;
import com.pip.chatbot.jooq.fortune.tables.Symbol;


/**
 * Convenience access to all tables in fortune
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>fortune.stock</code>.
     */
    public static final Stock STOCK = Stock.STOCK;

    /**
     * The table <code>fortune.symbol</code>.
     */
    public static final Symbol SYMBOL = Symbol.SYMBOL;
}
