/*
 * This file is generated by jOOQ.
 */
package com.pip.chatbot.jooq.food.tables.records;


import com.pip.chatbot.jooq.food.tables.Cuisine;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CuisineRecord extends UpdatableRecordImpl<CuisineRecord> implements Record1<String> {

    private static final long serialVersionUID = -76983016;

    /**
     * Setter for <code>food.cuisine.cuisine</code>.
     */
    public void setCuisine(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>food.cuisine.cuisine</code>.
     */
    public String getCuisine() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Cuisine.CUISINE.CUISINE_;
    }

    @Override
    public String component1() {
        return getCuisine();
    }

    @Override
    public String value1() {
        return getCuisine();
    }

    @Override
    public CuisineRecord value1(String value) {
        setCuisine(value);
        return this;
    }

    @Override
    public CuisineRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CuisineRecord
     */
    public CuisineRecord() {
        super(Cuisine.CUISINE);
    }

    /**
     * Create a detached, initialised CuisineRecord
     */
    public CuisineRecord(String cuisine) {
        super(Cuisine.CUISINE);

        set(0, cuisine);
    }
}
