/*
 * This file is generated by jOOQ.
 */
package com.pip.chatbot.jooq.food.tables.records;


import com.pip.chatbot.jooq.food.tables.MenuDish;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MenuDishRecord extends UpdatableRecordImpl<MenuDishRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 66768433;

    /**
     * Setter for <code>food.menu_dish.menu_id</code>.
     */
    public void setMenuId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>food.menu_dish.menu_id</code>.
     */
    public Integer getMenuId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>food.menu_dish.dish_id</code>.
     */
    public void setDishId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>food.menu_dish.dish_id</code>.
     */
    public Integer getDishId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return MenuDish.MENU_DISH.MENU_ID;
    }

    @Override
    public Field<Integer> field2() {
        return MenuDish.MENU_DISH.DISH_ID;
    }

    @Override
    public Integer component1() {
        return getMenuId();
    }

    @Override
    public Integer component2() {
        return getDishId();
    }

    @Override
    public Integer value1() {
        return getMenuId();
    }

    @Override
    public Integer value2() {
        return getDishId();
    }

    @Override
    public MenuDishRecord value1(Integer value) {
        setMenuId(value);
        return this;
    }

    @Override
    public MenuDishRecord value2(Integer value) {
        setDishId(value);
        return this;
    }

    @Override
    public MenuDishRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MenuDishRecord
     */
    public MenuDishRecord() {
        super(MenuDish.MENU_DISH);
    }

    /**
     * Create a detached, initialised MenuDishRecord
     */
    public MenuDishRecord(Integer menuId, Integer dishId) {
        super(MenuDish.MENU_DISH);

        set(0, menuId);
        set(1, dishId);
    }
}
