/*
 * This file is generated by jOOQ.
 */
package com.pip.chatbot.jooq.food.tables.records;


import com.pip.chatbot.jooq.food.tables.RestaurantCuisine;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RestaurantCuisineRecord extends UpdatableRecordImpl<RestaurantCuisineRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -1994533417;

    /**
     * Setter for <code>food.restaurant_cuisine.restaurant_id</code>.
     */
    public void setRestaurantId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>food.restaurant_cuisine.restaurant_id</code>.
     */
    public Integer getRestaurantId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>food.restaurant_cuisine.cuisine_id</code>.
     */
    public void setCuisineId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>food.restaurant_cuisine.cuisine_id</code>.
     */
    public Integer getCuisineId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return RestaurantCuisine.RESTAURANT_CUISINE.RESTAURANT_ID;
    }

    @Override
    public Field<Integer> field2() {
        return RestaurantCuisine.RESTAURANT_CUISINE.CUISINE_ID;
    }

    @Override
    public Integer component1() {
        return getRestaurantId();
    }

    @Override
    public Integer component2() {
        return getCuisineId();
    }

    @Override
    public Integer value1() {
        return getRestaurantId();
    }

    @Override
    public Integer value2() {
        return getCuisineId();
    }

    @Override
    public RestaurantCuisineRecord value1(Integer value) {
        setRestaurantId(value);
        return this;
    }

    @Override
    public RestaurantCuisineRecord value2(Integer value) {
        setCuisineId(value);
        return this;
    }

    @Override
    public RestaurantCuisineRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RestaurantCuisineRecord
     */
    public RestaurantCuisineRecord() {
        super(RestaurantCuisine.RESTAURANT_CUISINE);
    }

    /**
     * Create a detached, initialised RestaurantCuisineRecord
     */
    public RestaurantCuisineRecord(Integer restaurantId, Integer cuisineId) {
        super(RestaurantCuisine.RESTAURANT_CUISINE);

        set(0, restaurantId);
        set(1, cuisineId);
    }
}
