/*
 * This file is generated by jOOQ.
 */
package com.pip.chatbot.jooq.jokes;


import com.pip.chatbot.jooq.jokes.tables.Category;
import com.pip.chatbot.jooq.jokes.tables.Joke;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jokes extends SchemaImpl {

    private static final long serialVersionUID = -1127075373;

    /**
     * The reference instance of <code>jokes</code>
     */
    public static final Jokes JOKES = new Jokes();

    /**
     * The table <code>jokes.category</code>.
     */
    public final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>jokes.joke</code>.
     */
    public final Joke JOKE = Joke.JOKE;

    /**
     * No further instances allowed
     */
    private Jokes() {
        super("jokes", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.JOKE_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Category.CATEGORY,
            Joke.JOKE);
    }
}
