/*
 * This file is generated by jOOQ.
 */
package com.pip.chatbot.jooq.jokes;


import com.pip.chatbot.jooq.jokes.tables.Joke;


/**
 * Convenience access to all tables in jokes
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jokes.joke</code>.
     */
    public static final Joke JOKE = Joke.JOKE;
}
