/*
 * This file is generated by jOOQ.
 */
package com.pip.chatbot.jooq.jokes;


import com.pip.chatbot.jooq.jokes.tables.Category;
import com.pip.chatbot.jooq.jokes.tables.Joke;
import com.pip.chatbot.jooq.jokes.tables.Mark;


/**
 * Convenience access to all tables in jokes
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jokes.category</code>.
     */
    public static final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>jokes.joke</code>.
     */
    public static final Joke JOKE = Joke.JOKE;

    /**
     * The table <code>jokes.mark</code>.
     */
    public static final Mark MARK = Mark.MARK;
}
