/*
 * This file is generated by jOOQ.
 */
package com.pip.chatbot.jooq.food;


import com.pip.chatbot.jooq.DefaultCatalog;
import com.pip.chatbot.jooq.food.tables.City;
import com.pip.chatbot.jooq.food.tables.Country;
import com.pip.chatbot.jooq.food.tables.Cuisine;
import com.pip.chatbot.jooq.food.tables.Dish;
import com.pip.chatbot.jooq.food.tables.MarkFood;
import com.pip.chatbot.jooq.food.tables.Restaurant;
import com.pip.chatbot.jooq.food.tables.RestaurantCuisine;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Food extends SchemaImpl {

    private static final long serialVersionUID = 1131438303;

    /**
     * The reference instance of <code>food</code>
     */
    public static final Food FOOD = new Food();

    /**
     * The table <code>food.city</code>.
     */
    public final City CITY = City.CITY;

    /**
     * The table <code>food.country</code>.
     */
    public final Country COUNTRY = Country.COUNTRY;

    /**
     * The table <code>food.cuisine</code>.
     */
    public final Cuisine CUISINE = Cuisine.CUISINE;

    /**
     * The table <code>food.dish</code>.
     */
    public final Dish DISH = Dish.DISH;

    /**
     * The table <code>food.mark_food</code>.
     */
    public final MarkFood MARK_FOOD = MarkFood.MARK_FOOD;

    /**
     * The table <code>food.restaurant</code>.
     */
    public final Restaurant RESTAURANT = Restaurant.RESTAURANT;

    /**
     * The table <code>food.restaurant_cuisine</code>.
     */
    public final RestaurantCuisine RESTAURANT_CUISINE = RestaurantCuisine.RESTAURANT_CUISINE;

    /**
     * No further instances allowed
     */
    private Food() {
        super("food", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.CITY_ID_SEQ,
            Sequences.DISH_ID_SEQ,
            Sequences.MARK_FOOD_ID_SEQ,
            Sequences.RESTAURANT_CITY_ID_SEQ,
            Sequences.RESTAURANT_CUISINE_RESTAURANT_ID_SEQ,
            Sequences.RESTAURANT_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            City.CITY,
            Country.COUNTRY,
            Cuisine.CUISINE,
            Dish.DISH,
            MarkFood.MARK_FOOD,
            Restaurant.RESTAURANT,
            RestaurantCuisine.RESTAURANT_CUISINE);
    }
}
