/*
 * This file is generated by jOOQ.
 */
package com.pip.chatbot.jooq.food;


import com.pip.chatbot.jooq.food.tables.City;
import com.pip.chatbot.jooq.food.tables.Country;
import com.pip.chatbot.jooq.food.tables.Cuisine;
import com.pip.chatbot.jooq.food.tables.Dish;
import com.pip.chatbot.jooq.food.tables.Menu;
import com.pip.chatbot.jooq.food.tables.MenuDish;
import com.pip.chatbot.jooq.food.tables.Restaurant;
import com.pip.chatbot.jooq.food.tables.RestaurantCuisine;
import com.pip.chatbot.jooq.food.tables.records.CityRecord;
import com.pip.chatbot.jooq.food.tables.records.CountryRecord;
import com.pip.chatbot.jooq.food.tables.records.CuisineRecord;
import com.pip.chatbot.jooq.food.tables.records.DishRecord;
import com.pip.chatbot.jooq.food.tables.records.MenuDishRecord;
import com.pip.chatbot.jooq.food.tables.records.MenuRecord;
import com.pip.chatbot.jooq.food.tables.records.RestaurantCuisineRecord;
import com.pip.chatbot.jooq.food.tables.records.RestaurantRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>food</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CityRecord, Integer> IDENTITY_CITY = Identities0.IDENTITY_CITY;
    public static final Identity<CountryRecord, Integer> IDENTITY_COUNTRY = Identities0.IDENTITY_COUNTRY;
    public static final Identity<CuisineRecord, Integer> IDENTITY_CUISINE = Identities0.IDENTITY_CUISINE;
    public static final Identity<DishRecord, Integer> IDENTITY_DISH = Identities0.IDENTITY_DISH;
    public static final Identity<MenuRecord, Integer> IDENTITY_MENU = Identities0.IDENTITY_MENU;
    public static final Identity<MenuDishRecord, Integer> IDENTITY_MENU_DISH = Identities0.IDENTITY_MENU_DISH;
    public static final Identity<RestaurantRecord, Integer> IDENTITY_RESTAURANT = Identities0.IDENTITY_RESTAURANT;
    public static final Identity<RestaurantCuisineRecord, Integer> IDENTITY_RESTAURANT_CUISINE = Identities0.IDENTITY_RESTAURANT_CUISINE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CityRecord> CITY_PKEY = UniqueKeys0.CITY_PKEY;
    public static final UniqueKey<CountryRecord> COUNTRY_PKEY = UniqueKeys0.COUNTRY_PKEY;
    public static final UniqueKey<CuisineRecord> CUISINE_PKEY = UniqueKeys0.CUISINE_PKEY;
    public static final UniqueKey<DishRecord> DISH_PKEY = UniqueKeys0.DISH_PKEY;
    public static final UniqueKey<MenuRecord> MENU_PKEY = UniqueKeys0.MENU_PKEY;
    public static final UniqueKey<MenuDishRecord> RESTAURANT_CUISINE_PRIMARYKEY = UniqueKeys0.RESTAURANT_CUISINE_PRIMARYKEY;
    public static final UniqueKey<RestaurantRecord> RESTAURANT_PKEY = UniqueKeys0.RESTAURANT_PKEY;
    public static final UniqueKey<RestaurantCuisineRecord> RESTAURANT_CUISINE_PKEY = UniqueKeys0.RESTAURANT_CUISINE_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CityRecord, CountryRecord> CITY__CITY_COUNTRY_ID_FKEY = ForeignKeys0.CITY__CITY_COUNTRY_ID_FKEY;
    public static final ForeignKey<MenuRecord, RestaurantRecord> MENU__MENU_RESTAURANT_ID_FKEY = ForeignKeys0.MENU__MENU_RESTAURANT_ID_FKEY;
    public static final ForeignKey<MenuDishRecord, MenuRecord> MENU_DISH__MENU_DISH_MENU_ID_FKEY = ForeignKeys0.MENU_DISH__MENU_DISH_MENU_ID_FKEY;
    public static final ForeignKey<MenuDishRecord, DishRecord> MENU_DISH__MENU_DISH_DISH_ID_FKEY = ForeignKeys0.MENU_DISH__MENU_DISH_DISH_ID_FKEY;
    public static final ForeignKey<RestaurantRecord, CityRecord> RESTAURANT__RESTAURANT_CITY_ID_FKEY = ForeignKeys0.RESTAURANT__RESTAURANT_CITY_ID_FKEY;
    public static final ForeignKey<RestaurantCuisineRecord, RestaurantRecord> RESTAURANT_CUISINE__RESTAURANT_CUISINE_RESTAURANT_ID_FKEY = ForeignKeys0.RESTAURANT_CUISINE__RESTAURANT_CUISINE_RESTAURANT_ID_FKEY;
    public static final ForeignKey<RestaurantCuisineRecord, CuisineRecord> RESTAURANT_CUISINE__RESTAURANT_CUISINE_CUISINE_ID_FKEY = ForeignKeys0.RESTAURANT_CUISINE__RESTAURANT_CUISINE_CUISINE_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<CityRecord, Integer> IDENTITY_CITY = Internal.createIdentity(City.CITY, City.CITY.CITY_ID);
        public static Identity<CountryRecord, Integer> IDENTITY_COUNTRY = Internal.createIdentity(Country.COUNTRY, Country.COUNTRY.COUNTRY_ID);
        public static Identity<CuisineRecord, Integer> IDENTITY_CUISINE = Internal.createIdentity(Cuisine.CUISINE, Cuisine.CUISINE.CUISINE_ID);
        public static Identity<DishRecord, Integer> IDENTITY_DISH = Internal.createIdentity(Dish.DISH, Dish.DISH.DISH_ID);
        public static Identity<MenuRecord, Integer> IDENTITY_MENU = Internal.createIdentity(Menu.MENU, Menu.MENU.MENU_ID);
        public static Identity<MenuDishRecord, Integer> IDENTITY_MENU_DISH = Internal.createIdentity(MenuDish.MENU_DISH, MenuDish.MENU_DISH.MENU_ID);
        public static Identity<RestaurantRecord, Integer> IDENTITY_RESTAURANT = Internal.createIdentity(Restaurant.RESTAURANT, Restaurant.RESTAURANT.RESTAURANT_ID);
        public static Identity<RestaurantCuisineRecord, Integer> IDENTITY_RESTAURANT_CUISINE = Internal.createIdentity(RestaurantCuisine.RESTAURANT_CUISINE, RestaurantCuisine.RESTAURANT_CUISINE.RESTAURANT_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<CityRecord> CITY_PKEY = Internal.createUniqueKey(City.CITY, "city_pkey", new TableField[] { City.CITY.CITY_ID }, true);
        public static final UniqueKey<CountryRecord> COUNTRY_PKEY = Internal.createUniqueKey(Country.COUNTRY, "country_pkey", new TableField[] { Country.COUNTRY.COUNTRY_ID }, true);
        public static final UniqueKey<CuisineRecord> CUISINE_PKEY = Internal.createUniqueKey(Cuisine.CUISINE, "cuisine_pkey", new TableField[] { Cuisine.CUISINE.CUISINE_ID }, true);
        public static final UniqueKey<DishRecord> DISH_PKEY = Internal.createUniqueKey(Dish.DISH, "dish_pkey", new TableField[] { Dish.DISH.DISH_ID }, true);
        public static final UniqueKey<MenuRecord> MENU_PKEY = Internal.createUniqueKey(Menu.MENU, "menu_pkey", new TableField[] { Menu.MENU.MENU_ID }, true);
        public static final UniqueKey<MenuDishRecord> RESTAURANT_CUISINE_PRIMARYKEY = Internal.createUniqueKey(MenuDish.MENU_DISH, "restaurant_cuisine_primarykey", new TableField[] { MenuDish.MENU_DISH.MENU_ID, MenuDish.MENU_DISH.DISH_ID }, true);
        public static final UniqueKey<RestaurantRecord> RESTAURANT_PKEY = Internal.createUniqueKey(Restaurant.RESTAURANT, "restaurant_pkey", new TableField[] { Restaurant.RESTAURANT.RESTAURANT_ID }, true);
        public static final UniqueKey<RestaurantCuisineRecord> RESTAURANT_CUISINE_PKEY = Internal.createUniqueKey(RestaurantCuisine.RESTAURANT_CUISINE, "restaurant_cuisine_pkey", new TableField[] { RestaurantCuisine.RESTAURANT_CUISINE.RESTAURANT_ID, RestaurantCuisine.RESTAURANT_CUISINE.CUISINE_ID }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<CityRecord, CountryRecord> CITY__CITY_COUNTRY_ID_FKEY = Internal.createForeignKey(Keys.COUNTRY_PKEY, City.CITY, "city_country_id_fkey", new TableField[] { City.CITY.COUNTRY_ID }, true);
        public static final ForeignKey<MenuRecord, RestaurantRecord> MENU__MENU_RESTAURANT_ID_FKEY = Internal.createForeignKey(Keys.RESTAURANT_PKEY, Menu.MENU, "menu_restaurant_id_fkey", new TableField[] { Menu.MENU.RESTAURANT_ID }, true);
        public static final ForeignKey<MenuDishRecord, MenuRecord> MENU_DISH__MENU_DISH_MENU_ID_FKEY = Internal.createForeignKey(Keys.MENU_PKEY, MenuDish.MENU_DISH, "menu_dish_menu_id_fkey", new TableField[] { MenuDish.MENU_DISH.MENU_ID }, true);
        public static final ForeignKey<MenuDishRecord, DishRecord> MENU_DISH__MENU_DISH_DISH_ID_FKEY = Internal.createForeignKey(Keys.DISH_PKEY, MenuDish.MENU_DISH, "menu_dish_dish_id_fkey", new TableField[] { MenuDish.MENU_DISH.DISH_ID }, true);
        public static final ForeignKey<RestaurantRecord, CityRecord> RESTAURANT__RESTAURANT_CITY_ID_FKEY = Internal.createForeignKey(Keys.CITY_PKEY, Restaurant.RESTAURANT, "restaurant_city_id_fkey", new TableField[] { Restaurant.RESTAURANT.CITY_ID }, true);
        public static final ForeignKey<RestaurantCuisineRecord, RestaurantRecord> RESTAURANT_CUISINE__RESTAURANT_CUISINE_RESTAURANT_ID_FKEY = Internal.createForeignKey(Keys.RESTAURANT_PKEY, RestaurantCuisine.RESTAURANT_CUISINE, "restaurant_cuisine_restaurant_id_fkey", new TableField[] { RestaurantCuisine.RESTAURANT_CUISINE.RESTAURANT_ID }, true);
        public static final ForeignKey<RestaurantCuisineRecord, CuisineRecord> RESTAURANT_CUISINE__RESTAURANT_CUISINE_CUISINE_ID_FKEY = Internal.createForeignKey(Keys.CUISINE_PKEY, RestaurantCuisine.RESTAURANT_CUISINE, "restaurant_cuisine_cuisine_id_fkey", new TableField[] { RestaurantCuisine.RESTAURANT_CUISINE.CUISINE_ID }, true);
    }
}
