/*
 * This file is generated by jOOQ.
 */
package com.pip.chatbot.jooq.food;


import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in food
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>food.dish_id_seq</code>
     */
    public static final Sequence<Integer> DISH_ID_SEQ = Internal.createSequence("dish_id_seq", Food.FOOD, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>food.menu_dish_dish_id_seq</code>
     */
    public static final Sequence<Integer> MENU_DISH_DISH_ID_SEQ = Internal.createSequence("menu_dish_dish_id_seq", Food.FOOD, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>food.menu_dish_menu_id_seq</code>
     */
    public static final Sequence<Integer> MENU_DISH_MENU_ID_SEQ = Internal.createSequence("menu_dish_menu_id_seq", Food.FOOD, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>food.menu_id_seq</code>
     */
    public static final Sequence<Integer> MENU_ID_SEQ = Internal.createSequence("menu_id_seq", Food.FOOD, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>food.menu_restaurant_id_seq</code>
     */
    public static final Sequence<Integer> MENU_RESTAURANT_ID_SEQ = Internal.createSequence("menu_restaurant_id_seq", Food.FOOD, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>food.restaurant_cuisine_restaurant_id_seq</code>
     */
    public static final Sequence<Integer> RESTAURANT_CUISINE_RESTAURANT_ID_SEQ = Internal.createSequence("restaurant_cuisine_restaurant_id_seq", Food.FOOD, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>food.restaurant_id_seq</code>
     */
    public static final Sequence<Integer> RESTAURANT_ID_SEQ = Internal.createSequence("restaurant_id_seq", Food.FOOD, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
