/*
 * This file is generated by jOOQ.
 */
package com.pip.chatbot.jooq.food;


import com.pip.chatbot.jooq.food.tables.City;
import com.pip.chatbot.jooq.food.tables.Country;
import com.pip.chatbot.jooq.food.tables.Cuisine;
import com.pip.chatbot.jooq.food.tables.Dish;
import com.pip.chatbot.jooq.food.tables.Menu;
import com.pip.chatbot.jooq.food.tables.MenuDish;
import com.pip.chatbot.jooq.food.tables.Restaurant;
import com.pip.chatbot.jooq.food.tables.RestaurantCuisine;


/**
 * Convenience access to all tables in food
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>food.city</code>.
     */
    public static final City CITY = City.CITY;

    /**
     * The table <code>food.country</code>.
     */
    public static final Country COUNTRY = Country.COUNTRY;

    /**
     * The table <code>food.cuisine</code>.
     */
    public static final Cuisine CUISINE = Cuisine.CUISINE;

    /**
     * The table <code>food.dish</code>.
     */
    public static final Dish DISH = Dish.DISH;

    /**
     * The table <code>food.menu</code>.
     */
    public static final Menu MENU = Menu.MENU;

    /**
     * The table <code>food.menu_dish</code>.
     */
    public static final MenuDish MENU_DISH = MenuDish.MENU_DISH;

    /**
     * The table <code>food.restaurant</code>.
     */
    public static final Restaurant RESTAURANT = Restaurant.RESTAURANT;

    /**
     * The table <code>food.restaurant_cuisine</code>.
     */
    public static final RestaurantCuisine RESTAURANT_CUISINE = RestaurantCuisine.RESTAURANT_CUISINE;
}
