/*
 * This file is generated by jOOQ.
 */
package com.pip.chatbot.jooq.food;


import com.pip.chatbot.jooq.food.tables.City;
import com.pip.chatbot.jooq.food.tables.Country;
import com.pip.chatbot.jooq.food.tables.Cuisine;
import com.pip.chatbot.jooq.food.tables.MarkRestaurant;
import com.pip.chatbot.jooq.food.tables.Restaurant;
import com.pip.chatbot.jooq.food.tables.RestaurantCuisine;


/**
 * Convenience access to all tables in food
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>food.city</code>.
     */
    public static final City CITY = City.CITY;

    /**
     * The table <code>food.country</code>.
     */
    public static final Country COUNTRY = Country.COUNTRY;

    /**
     * The table <code>food.cuisine</code>.
     */
    public static final Cuisine CUISINE = Cuisine.CUISINE;

    /**
     * The table <code>food.mark_restaurant</code>.
     */
    public static final MarkRestaurant MARK_RESTAURANT = MarkRestaurant.MARK_RESTAURANT;

    /**
     * The table <code>food.restaurant</code>.
     */
    public static final Restaurant RESTAURANT = Restaurant.RESTAURANT;

    /**
     * The table <code>food.restaurant_cuisine</code>.
     */
    public static final RestaurantCuisine RESTAURANT_CUISINE = RestaurantCuisine.RESTAURANT_CUISINE;
}
