/*
 * This file is generated by jOOQ.
 */
package com.pip.chatbot.jooq.fortune.tables;


import com.pip.chatbot.jooq.fortune.Fortune;
import com.pip.chatbot.jooq.fortune.Keys;
import com.pip.chatbot.jooq.fortune.tables.records.StockRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Stock extends TableImpl<StockRecord> {

    private static final long serialVersionUID = 1743128644;

    /**
     * The reference instance of <code>fortune.stock</code>
     */
    public static final Stock STOCK = new Stock();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StockRecord> getRecordType() {
        return StockRecord.class;
    }

    /**
     * The column <code>fortune.stock.id</code>.
     */
    public final TableField<StockRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('fortune.stock_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>fortune.stock.symbol</code>.
     */
    public final TableField<StockRecord, String> SYMBOL = createField(DSL.name("symbol"), org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>fortune.stock.value</code>.
     */
    public final TableField<StockRecord, Float> VALUE = createField(DSL.name("value"), org.jooq.impl.SQLDataType.REAL.nullable(false), this, "");

    /**
     * The column <code>fortune.stock.date</code>.
     */
    public final TableField<StockRecord, LocalDateTime> DATE = createField(DSL.name("date"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>fortune.stock.is_historical</code>.
     */
    public final TableField<StockRecord, Boolean> IS_HISTORICAL = createField(DSL.name("is_historical"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * Create a <code>fortune.stock</code> table reference
     */
    public Stock() {
        this(DSL.name("stock"), null);
    }

    /**
     * Create an aliased <code>fortune.stock</code> table reference
     */
    public Stock(String alias) {
        this(DSL.name(alias), STOCK);
    }

    /**
     * Create an aliased <code>fortune.stock</code> table reference
     */
    public Stock(Name alias) {
        this(alias, STOCK);
    }

    private Stock(Name alias, Table<StockRecord> aliased) {
        this(alias, aliased, null);
    }

    private Stock(Name alias, Table<StockRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Stock(Table<O> child, ForeignKey<O, StockRecord> key) {
        super(child, key, STOCK);
    }

    @Override
    public Schema getSchema() {
        return Fortune.FORTUNE;
    }

    @Override
    public Identity<StockRecord, Long> getIdentity() {
        return Keys.IDENTITY_STOCK;
    }

    @Override
    public UniqueKey<StockRecord> getPrimaryKey() {
        return Keys.STOCK_PKEY;
    }

    @Override
    public List<UniqueKey<StockRecord>> getKeys() {
        return Arrays.<UniqueKey<StockRecord>>asList(Keys.STOCK_PKEY);
    }

    @Override
    public List<ForeignKey<StockRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<StockRecord, ?>>asList(Keys.STOCK__STOCK_SYMBOL_FKEY);
    }

    public Symbol symbol() {
        return new Symbol(this, Keys.STOCK__STOCK_SYMBOL_FKEY);
    }

    @Override
    public Stock as(String alias) {
        return new Stock(DSL.name(alias), this);
    }

    @Override
    public Stock as(Name alias) {
        return new Stock(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Stock rename(String name) {
        return new Stock(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Stock rename(Name name) {
        return new Stock(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, Float, LocalDateTime, Boolean> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
