/*
 * This file is generated by jOOQ.
 */
package com.pip.chatbot.jooq.jokes.tables.records;


import com.pip.chatbot.jooq.jokes.tables.Category;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryRecord extends UpdatableRecordImpl<CategoryRecord> implements Record1<String> {

    private static final long serialVersionUID = 3853578;

    /**
     * Setter for <code>jokes.category.category</code>.
     */
    public void setCategory(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>jokes.category.category</code>.
     */
    public String getCategory() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Category.CATEGORY.CATEGORY_;
    }

    @Override
    public String component1() {
        return getCategory();
    }

    @Override
    public String value1() {
        return getCategory();
    }

    @Override
    public CategoryRecord value1(String value) {
        setCategory(value);
        return this;
    }

    @Override
    public CategoryRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CategoryRecord
     */
    public CategoryRecord() {
        super(Category.CATEGORY);
    }

    /**
     * Create a detached, initialised CategoryRecord
     */
    public CategoryRecord(String category) {
        super(Category.CATEGORY);

        set(0, category);
    }
}
