/*
 * This file is generated by jOOQ.
 */
package com.pip.chatbot.jooq.jokes.tables.records;


import com.pip.chatbot.jooq.jokes.tables.Joke;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JokeRecord extends UpdatableRecordImpl<JokeRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = -759085619;

    /**
     * Setter for <code>jokes.joke.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jokes.joke.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jokes.joke.category</code>.
     */
    public void setCategory(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jokes.joke.category</code>.
     */
    public String getCategory() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jokes.joke.joke</code>.
     */
    public void setJoke(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>jokes.joke.joke</code>.
     */
    public String getJoke() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Joke.JOKE.ID;
    }

    @Override
    public Field<String> field2() {
        return Joke.JOKE.CATEGORY;
    }

    @Override
    public Field<String> field3() {
        return Joke.JOKE.JOKE_;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCategory();
    }

    @Override
    public String component3() {
        return getJoke();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCategory();
    }

    @Override
    public String value3() {
        return getJoke();
    }

    @Override
    public JokeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public JokeRecord value2(String value) {
        setCategory(value);
        return this;
    }

    @Override
    public JokeRecord value3(String value) {
        setJoke(value);
        return this;
    }

    @Override
    public JokeRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JokeRecord
     */
    public JokeRecord() {
        super(Joke.JOKE);
    }

    /**
     * Create a detached, initialised JokeRecord
     */
    public JokeRecord(Integer id, String category, String joke) {
        super(Joke.JOKE);

        set(0, id);
        set(1, category);
        set(2, joke);
    }
}
