/*
 * This file is generated by jOOQ.
 */
package org.jooq.database;


import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.database.tables.Info;
import org.jooq.database.tables.records.InfoRecord;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>weather</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<InfoRecord, Integer> IDENTITY_INFO = Identities0.IDENTITY_INFO;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<InfoRecord> INFO_PKEY = UniqueKeys0.INFO_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<InfoRecord, Integer> IDENTITY_INFO = Internal.createIdentity(Info.INFO, Info.INFO.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<InfoRecord> INFO_PKEY = Internal.createUniqueKey(Info.INFO, "info_pkey", new TableField[] { Info.INFO.ID }, true);
    }
}
