/*
 * This file is generated by jOOQ.
 */
package org.jooq.database;


import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in weather
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>weather.info_id_seq</code>
     */
    public static final Sequence<Integer> INFO_ID_SEQ = Internal.createSequence("info_id_seq", Weather.WEATHER, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
