/*
 * This file is generated by jOOQ.
 */
package org.jooq.database;


import org.jooq.database.tables.Info;


/**
 * Convenience access to all tables in weather
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>weather.info</code>.
     */
    public static final Info INFO = Info.INFO;
}
