/*
 * This file is generated by jOOQ.
 */
package org.jooq.database;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.database.tables.Info;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Weather extends SchemaImpl {

    private static final long serialVersionUID = 193873280;

    /**
     * The reference instance of <code>weather</code>
     */
    public static final Weather WEATHER = new Weather();

    /**
     * The table <code>weather.info</code>.
     */
    public final Info INFO = Info.INFO;

    /**
     * No further instances allowed
     */
    private Weather() {
        super("weather", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.INFO_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Info.INFO);
    }
}
